syntax = "proto3";

package blog;

import "google/protobuf/timestamp.proto";

// Сервис работы с пользователем
service UserService {
  // Регистрация пользователя
  rpc RegisterUser(RegisterRequest) returns (RegisterResponse);

  // Авторизация пользователя
  rpc LoginUser(LoginRequest) returns (LoginResponse);

  // Выход из аккаунта
  rpc LogoutUser(LogoutRequest) returns (LogoutResponse);
}

message RegisterRequest {
  string email = 1;
  string username = 2;
  string password = 3;
}

message RegisterResponse {
  bool resp = 1;
}

message LoginRequest {
  string username = 1;
  string password = 2;
}

message LoginResponse {
  bool status = 1;
}

message LogoutRequest {}
message LogoutResponse {
  bool status = 1;
}

service PostService {
  rpc CreatePost(CreatePostRequest) returns (CreatePostResponse);
  rpc GetPost(GetPostRequest) returns (GetPostResponse);
  rpc UpdatePost(UpdatePostRequest) returns (UpdatePostResponse);
  rpc DeletePost(DeletePostRequest) returns (DeletePostResponse);
  rpc ListPosts(ListPostRequest) returns (ListPostResponse);
}

message CreatePostRequest {
  string head = 1;
  string body = 2;
}

message CreatePostResponse {
  string post_id = 1;
}

message GetPostRequest {
  string post_id = 1;
}

message GetPostResponse {
  string head = 1;
  string body = 2;
  string author = 3;
}

message UpdatePostRequest {
  string post_id = 1;
  string head = 2;
  string body = 3;
}

message UpdatePostResponse {
  bool status = 1;
}

message DeletePostRequest {
  string post_id = 1;
}

message DeletePostResponse {
  bool status = 1;
}

message ListPostRequest {
  google.protobuf.Timestamp dt_from = 1;
  google.protobuf.Timestamp dt_to = 2;
  int64 limit = 3;
}

message ListPostResponse {
  repeated GetPostResponse posts = 1;
}